### ISSUE TITLE
Create a LICENSE file

### ISSUE THREAD

**Issue by munnerz** [munnerz/goautoneg#1]
In order to make it easier for automated license checkers to determine what license this repository is under, it'd be useful to have a LICENSE file in the root of the repository.

It's currently stored only in the README, meaning it may get pruned by some vendor management tooling.

Would copying the license into a separate `LICENSE` file make sense? cc @dims

**Comment by dims** [comment]
+1 from me! https://apache.org/dev/apply-license.html#new
